# Generated by Django 2.0.6 on 2018-06-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baranggay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baranggay', models.CharField(max_length=200)),
                ('baranggay_date_created', models.DateTimeField(verbose_name='date_created')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Recidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('house_no', models.CharField(max_length=200)),
                ('recidence_date_created', models.DateTimeField(verbose_name='date_created')),
                ('baranggay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cli_example.Baranggay')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cli_example.City')),
            ],
        ),
        migrations.AddField(
            model_name='baranggay',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cli_example.City'),
        ),
    ]
