# Generated by Django 2.0.3 on 2018-06-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cli_example', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recidence',
            new_name='Residence',
        ),
        migrations.RenameField(
            model_name='residence',
            old_name='recidence_date_created',
            new_name='residence_date_created',
        ),
    ]
