# Generated by Django 2.1.3 on 2018-11-30 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cli_example', '0004_auto_20180615_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baranggay',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='baranggay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cli_example.Baranggay'),
        ),
    ]
