# Generated by Django 2.1.3 on 2018-11-30 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cli_example', '0007_auto_20181130_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cli_example.Province'),
        ),
        migrations.AlterField(
            model_name='city',
            name='date_created',
            field=models.DateTimeField(verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='country',
            name='date_created',
            field=models.DateTimeField(verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='island',
            name='date_created',
            field=models.DateTimeField(verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='province',
            name='date_created',
            field=models.DateTimeField(verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='region',
            name='date_created',
            field=models.DateTimeField(verbose_name='date_created'),
        ),
    ]
