# Generated by Django 2.1.3 on 2018-11-30 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cli_example', '0009_province_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='island',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cli_example.Island'),
        ),
    ]
