# Generated by Django 2.1.3 on 2018-11-30 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cli_example', '0010_region_island'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cli_example.Country'),
        ),
    ]
