# Generated by Django 2.1.3 on 2018-11-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cli_example', '0011_island_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baranggay',
            name='city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='island',
            name='country',
        ),
        migrations.RemoveField(
            model_name='province',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='island',
        ),
        migrations.AddField(
            model_name='city',
            name='baranggay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cli_example.Baranggay'),
        ),
        migrations.AddField(
            model_name='island',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cli_example.Region'),
        ),
        migrations.AddField(
            model_name='province',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cli_example.City'),
        ),
        migrations.AddField(
            model_name='region',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cli_example.Province'),
        ),
    ]
