# Generated by Django 2.1.3 on 2018-11-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cli_example', '0016_remove_province_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cli_example.City'),
        ),
    ]
